language: generic
sudo: require
services:
  - docker

before_install:
  - docker build -t thekapitankorek/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true thekapitankorek/docker-react npm run test
